apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
  spec:
    containers:
    - name: hello
      image: jaganthoutam/hello:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: hello
---
#service
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - name: hello
    protocol: TCP
    nodePort: 30400
    port: 5000
    targetPort: 5000
